const projects={drift:{kicker:'01 / Full-stack · Computer vision',title:'DRIFT — Drone Infrastructure Inspector',summary:'A full-stack inspection platform that turns drone evidence into an accountable review and reporting workflow.',details:'<strong>What I built</strong><ul><li>9 operational workspaces across identity, assets, missions, findings, review, and accountability.</li><li>A 12-entity-group PostgreSQL/Drizzle schema with authenticated ingestion endpoints.</li><li>A 4-model detection layer using local YOLO models and Roboflow APIs.</li><li>A 9-stage evidence-to-report pipeline with GPS/EXIF extraction, geospatial correlation, explainable severity scoring, PDF generation, and live SSE updates.</li></ul>',link:'https://github.com/RidhimaKulashriz/DRIFT'},canopy:{kicker:'02 / Geospatial · Climate intelligence',title:'DelhiCanopy AI',summary:'A decision-support platform helping cities understand green cover, heat risk, and tree loss across Delhi wards.',details:'<strong>What I built</strong><ul><li>A 10-route React and TypeScript product using satellite-derived green-cover data and heat-risk analytics.</li><li>Computer-vision-based tree-loss alerts presented through a clear ward-level interface.</li><li>TrustOps: a six-stage gate for evidence capture, credibility scoring, red-team challenge, review assignment, release control, and audit receipt.</li><li>An ESP32 field-instrument prototype tracking PM1, PM2.5, PM10, and NO₂.</li></ul>',link:'https://github.com/RidhimaKulashriz/Delhi-Canopy-Sambhav'},stockp:{kicker:'03 / Data product · Finance',title:'StockP',summary:'A three-service financial analytics experience built around clear information architecture and authenticated data flows.',details:'<strong>What I built</strong><ul><li>React marketing site and Material UI dashboard.</li><li>Express and MongoDB API with Mongoose.</li><li>JWT/Passport authentication and Chart.js financial visualizations.</li></ul>',link:'https://github.com/RidhimaKulashriz/stockp'},gov:{kicker:'04 / Retrieval · Public data',title:'Gov RAG AI',summary:'A retrieval-augmented generation pipeline for natural-language querying over government datasets.',details:'<strong>What I built</strong><ul><li>Vector embeddings and semantic search over public datasets.</li><li>LangChain-orchestrated retrieval and LLM response pipeline.</li><li>A foundation for making structured government information easier to explore.</li></ul>',link:'https://github.com/RidhimaKulashriz/gov-rag-ai'},guardian:{kicker:'05 / Edge · Security',title:'Guardian AI',summary:'A smart-farm security system bringing real-time object detection to an edge device.',details:'<strong>What I built</strong><ul><li>YOLOv8 inference on Raspberry Pi for animal detection.</li><li>Hardware-triggered alerting for automated perimeter surveillance.</li><li>An applied bridge between computer vision, Python, Arduino, and physical systems.</li></ul>',link:'https://github.com/RidhimaKulashriz/guardian_ai'}};
const modal=document.getElementById('projectModal');
function openProject(key){const p=projects[key];document.getElementById('modalKicker').textContent=p.kicker;document.getElementById('modalTitle').textContent=p.title;document.getElementById('modalSummary').textContent=p.summary;document.getElementById('modalDetails').innerHTML=p.details;document.getElementById('modalLink').href=p.link;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';document.getElementById('modalClose').focus()}
function closeProject(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.querySelectorAll('.open-project').forEach(b=>b.addEventListener('click',()=>openProject(b.closest('.project-card').dataset.project)));
document.getElementById('modalClose').addEventListener('click',closeProject);document.querySelector('.modal-backdrop').addEventListener('click',closeProject);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeProject()});
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));button.classList.add('active');const filter=button.dataset.filter;document.querySelectorAll('.project-card').forEach(card=>{card.classList.toggle('hidden',filter!=='all'&&!card.dataset.category.includes(filter))})}));
document.querySelectorAll('.tab').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.remove('active'));button.classList.add('active');document.getElementById(button.dataset.tab).classList.add('active')}));
const menuButton=document.getElementById('menuButton'),mobileNav=document.getElementById('mobileNav');menuButton.addEventListener('click',()=>{const open=mobileNav.classList.toggle('open');menuButton.setAttribute('aria-expanded',open)});mobileNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobileNav.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('visible')}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
window.addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-window.innerHeight;document.getElementById('progressBar').style.width=(window.scrollY/h*100)+'%'});
